In [13]:
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import metrics
import pandas as pd

In [7]:
from sklearn.datasets import load_boston

In [10]:
boston=load_boston()
boston

{'DESCR': ".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000\n        - PTRATIO  pupil-teacher ratio by town\n        - B        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\n        - LSTAT    % lower status of the population\n        - MEDV     Median value of owner-occupied homes in $1000's\n\n    :Missing Attribute Values: None\n\n    :Creator: Harrison, D. and Rubinfeld, D.L.\n\nThis is a copy of UCI ML housing dataset.\nhttps://archive.ics.uci.edu/ml/machine-learning-databases/housing/\n\n\nThis dataset was taken from the StatLib library which is maintained at Carnegie Mellon University.\n\nThe Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic\nprices and the demand for clean air', J. Environ. Economics & Management,\nvol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics\n...', Wiley, 1980.   N.B. Various transformations are used in the table on\npages 244-261 of the latter.\n\nThe Boston house-price data has been used in many machine learning papers that address regression\nproblems.   \n     \n.. topic:: References\n\n   - Belsley, Kuh & Welsch, 'Regression diagnostics: Identifying Influential Data and Sources of Collinearity', Wiley, 1980. 244-261.\n   - Quinlan,R. (1993). Combining Instance-Based and Model-Based Learning. In Proceedings on the Tenth International Conference of Machine Learning, 236-243, University of Massachusetts, Amherst. Morgan Kaufmann.\n",
 'data': array([[  6.32000000e-03,   1.80000000e+01,   2.31000000e+00, ...,
           1.53000000e+01,   3.96900000e+02,   4.98000000e+00],
        [  2.73100000e-02,   0.00000000e+00,   7.07000000e+00, ...,
           1.78000000e+01,   3.96900000e+02,   9.14000000e+00],
        [  2.72900000e-02,   0.00000000e+00,   7.07000000e+00, ...,
           1.78000000e+01,   3.92830000e+02,   4.03000000e+00],
        ...,
        [  6.07600000e-02,   0.00000000e+00,   1.19300000e+01, ...,
           2.10000000e+01,   3.96900000e+02,   5.64000000e+00],
        [  1.09590000e-01,   0.00000000e+00,   1.19300000e+01, ...,
           2.10000000e+01,   3.93450000e+02,   6.48000000e+00],
        [  4.74100000e-02,   0.00000000e+00,   1.19300000e+01, ...,
           2.10000000e+01,   3.96900000e+02,   7.88000000e+00]]),
 'feature_names': array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
        'TAX', 'PTRATIO', 'B', 'LSTAT'],
       dtype='|S7'),
 'filename': 'C:\\Users\\My Dell\\Anaconda2\\lib\\site-packages\\sklearn\\datasets\\data\\boston_house_prices.csv',
 'target': array([ 24. ,  21.6,  34.7,  33.4,  36.2,  28.7,  22.9,  27.1,  16.5,
         18.9,  15. ,  18.9,  21.7,  20.4,  18.2,  19.9,  23.1,  17.5,
         20.2,  18.2,  13.6,  19.6,  15.2,  14.5,  15.6,  13.9,  16.6,
         14.8,  18.4,  21. ,  12.7,  14.5,  13.2,  13.1,  13.5,  18.9,
         20. ,  21. ,  24.7,  30.8,  34.9,  26.6,  25.3,  24.7,  21.2,
         19.3,  20. ,  16.6,  14.4,  19.4,  19.7,  20.5,  25. ,  23.4,
         18.9,  35.4,  24.7,  31.6,  23.3,  19.6,  18.7,  16. ,  22.2,
         25. ,  33. ,  23.5,  19.4,  22. ,  17.4,  20.9,  24.2,  21.7,
         22.8,  23.4,  24.1,  21.4,  20. ,  20.8,  21.2,  20.3,  28. ,
         23.9,  24.8,  22.9,  23.9,  26.6,  22.5,  22.2,  23.6,  28.7,
         22.6,  22. ,  22.9,  25. ,  20.6,  28.4,  21.4,  38.7,  43.8,
         33.2,  27.5,  26.5,  18.6,  19.3,  20.1,  19.5,  19.5,  20.4,
         19.8,  19.4,  21.7,  22.8,  18.8,  18.7,  18.5,  18.3,  21.2,
         19.2,  20.4,  19.3,  22. ,  20.3,  20.5,  17.3,  18.8,  21.4,
         15.7,  16.2,  18. ,  14.3,  19.2,  19.6,  23. ,  18.4,  15.6,
         18.1,  17.4,  17.1,  13.3,  17.8,  14. ,  14.4,  13.4,  15.6,
         11.8,  13.8,  15.6,  14.6,  17.8,  15.4,  21.5,  19.6,  15.3,
         19.4,  17. ,  15.6,  13.1,  41.3,  24.3,  23.3,  27. ,  50. ,
         50. ,  50. ,  22.7,  25. ,  50. ,  23.8,  23.8,  22.3,  17.4,
         19.1,  23.1,  23.6,  22.6,  29.4,  23.2,  24.6,  29.9,  37.2,
         39.8,  36.2,  37.9,  32.5,  26.4,  29.6,  50. ,  32. ,  29.8,
         34.9,  37. ,  30.5,  36.4,  31.1,  29.1,  50. ,  33.3,  30.3,
         34.6,  34.9,  32.9,  24.1,  42.3,  48.5,  50. ,  22.6,  24.4,
         22.5,  24.4,  20. ,  21.7,  19.3,  22.4,  28.1,  23.7,  25. ,
         23.3,  28.7,  21.5,  23. ,  26.7,  21.7,  27.5,  30.1,  44.8,
         50. ,  37.6,  31.6,  46.7,  31.5,  24.3,  31.7,  41.7,  48.3,
         29. ,  24. ,  25.1,  31.5,  23.7,  23.3,  22. ,  20.1,  22.2,
         23.7,  17.6,  18.5,  24.3,  20.5,  24.5,  26.2,  24.4,  24.8,
         29.6,  42.8,  21.9,  20.9,  44. ,  50. ,  36. ,  30.1,  33.8,
         43.1,  48.8,  31. ,  36.5,  22.8,  30.7,  50. ,  43.5,  20.7,
         21.1,  25.2,  24.4,  35.2,  32.4,  32. ,  33.2,  33.1,  29.1,
         35.1,  45.4,  35.4,  46. ,  50. ,  32.2,  22. ,  20.1,  23.2,
         22.3,  24.8,  28.5,  37.3,  27.9,  23.9,  21.7,  28.6,  27.1,
         20.3,  22.5,  29. ,  24.8,  22. ,  26.4,  33.1,  36.1,  28.4,
         33.4,  28.2,  22.8,  20.3,  16.1,  22.1,  19.4,  21.6,  23.8,
         16.2,  17.8,  19.8,  23.1,  21. ,  23.8,  23.1,  20.4,  18.5,
         25. ,  24.6,  23. ,  22.2,  19.3,  22.6,  19.8,  17.1,  19.4,
         22.2,  20.7,  21.1,  19.5,  18.5,  20.6,  19. ,  18.7,  32.7,
         16.5,  23.9,  31.2,  17.5,  17.2,  23.1,  24.5,  26.6,  22.9,
         24.1,  18.6,  30.1,  18.2,  20.6,  17.8,  21.7,  22.7,  22.6,
         25. ,  19.9,  20.8,  16.8,  21.9,  27.5,  21.9,  23.1,  50. ,
         50. ,  50. ,  50. ,  50. ,  13.8,  13.8,  15. ,  13.9,  13.3,
         13.1,  10.2,  10.4,  10.9,  11.3,  12.3,   8.8,   7.2,  10.5,
          7.4,  10.2,  11.5,  15.1,  23.2,   9.7,  13.8,  12.7,  13.1,
         12.5,   8.5,   5. ,   6.3,   5.6,   7.2,  12.1,   8.3,   8.5,
          5. ,  11.9,  27.9,  17.2,  27.5,  15. ,  17.2,  17.9,  16.3,
          7. ,   7.2,   7.5,  10.4,   8.8,   8.4,  16.7,  14.2,  20.8,
         13.4,  11.7,   8.3,  10.2,  10.9,  11. ,   9.5,  14.5,  14.1,
         16.1,  14.3,  11.7,  13.4,   9.6,   8.7,   8.4,  12.8,  10.5,
         17.1,  18.4,  15.4,  10.8,  11.8,  14.9,  12.6,  14.1,  13. ,
         13.4,  15.2,  16.1,  17.8,  14.9,  14.1,  12.7,  13.5,  14.9,
         20. ,  16.4,  17.7,  19.5,  20.2,  21.4,  19.9,  19. ,  19.1,
         19.1,  20.1,  19.9,  19.6,  23.2,  29.8,  13.8,  13.3,  16.7,
         12. ,  14.6,  21.4,  23. ,  23.7,  25. ,  21.8,  20.6,  21.2,
         19.1,  20.6,  15.2,   7. ,   8.1,  13.6,  20.1,  21.8,  24.5,
         23.1,  19.7,  18.3,  21.2,  17.5,  16.8,  22.4,  20.6,  23.9,
         22. ,  11.9])}

In [14]:
X=pd.DataFrame(boston.data,columns=boston.feature_names)
X.head

<bound method DataFrame.head of          CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
0     0.00632  18.0   2.31   0.0  0.538  6.575   65.2  4.0900   1.0  296.0
1     0.02731   0.0   7.07   0.0  0.469  6.421   78.9  4.9671   2.0  242.0
2     0.02729   0.0   7.07   0.0  0.469  7.185   61.1  4.9671   2.0  242.0
3     0.03237   0.0   2.18   0.0  0.458  6.998   45.8  6.0622   3.0  222.0
4     0.06905   0.0   2.18   0.0  0.458  7.147   54.2  6.0622   3.0  222.0
5     0.02985   0.0   2.18   0.0  0.458  6.430   58.7  6.0622   3.0  222.0
6     0.08829  12.5   7.87   0.0  0.524  6.012   66.6  5.5605   5.0  311.0
7     0.14455  12.5   7.87   0.0  0.524  6.172   96.1  5.9505   5.0  311.0
8     0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821   5.0  311.0
9     0.17004  12.5   7.87   0.0  0.524  6.004   85.9  6.5921   5.0  311.0
10    0.22489  12.5   7.87   0.0  0.524  6.377   94.3  6.3467   5.0  311.0
11    0.11747  12.5   7.87   0.0  0.524  6.009   82.9  6.2267   5.0  311.0
12    0.09378  12.5   7.87   0.0  0.524  5.889   39.0  5.4509   5.0  311.0
13    0.62976   0.0   8.14   0.0  0.538  5.949   61.8  4.7075   4.0  307.0
14    0.63796   0.0   8.14   0.0  0.538  6.096   84.5  4.4619   4.0  307.0
15    0.62739   0.0   8.14   0.0  0.538  5.834   56.5  4.4986   4.0  307.0
16    1.05393   0.0   8.14   0.0  0.538  5.935   29.3  4.4986   4.0  307.0
17    0.78420   0.0   8.14   0.0  0.538  5.990   81.7  4.2579   4.0  307.0
18    0.80271   0.0   8.14   0.0  0.538  5.456   36.6  3.7965   4.0  307.0
19    0.72580   0.0   8.14   0.0  0.538  5.727   69.5  3.7965   4.0  307.0
20    1.25179   0.0   8.14   0.0  0.538  5.570   98.1  3.7979   4.0  307.0
21    0.85204   0.0   8.14   0.0  0.538  5.965   89.2  4.0123   4.0  307.0
22    1.23247   0.0   8.14   0.0  0.538  6.142   91.7  3.9769   4.0  307.0
23    0.98843   0.0   8.14   0.0  0.538  5.813  100.0  4.0952   4.0  307.0
24    0.75026   0.0   8.14   0.0  0.538  5.924   94.1  4.3996   4.0  307.0
25    0.84054   0.0   8.14   0.0  0.538  5.599   85.7  4.4546   4.0  307.0
26    0.67191   0.0   8.14   0.0  0.538  5.813   90.3  4.6820   4.0  307.0
27    0.95577   0.0   8.14   0.0  0.538  6.047   88.8  4.4534   4.0  307.0
28    0.77299   0.0   8.14   0.0  0.538  6.495   94.4  4.4547   4.0  307.0
29    1.00245   0.0   8.14   0.0  0.538  6.674   87.3  4.2390   4.0  307.0
..        ...   ...    ...   ...    ...    ...    ...     ...   ...    ...
476   4.87141   0.0  18.10   0.0  0.614  6.484   93.6  2.3053  24.0  666.0
477  15.02340   0.0  18.10   0.0  0.614  5.304   97.3  2.1007  24.0  666.0
478  10.23300   0.0  18.10   0.0  0.614  6.185   96.7  2.1705  24.0  666.0
479  14.33370   0.0  18.10   0.0  0.614  6.229   88.0  1.9512  24.0  666.0
480   5.82401   0.0  18.10   0.0  0.532  6.242   64.7  3.4242  24.0  666.0
481   5.70818   0.0  18.10   0.0  0.532  6.750   74.9  3.3317  24.0  666.0
482   5.73116   0.0  18.10   0.0  0.532  7.061   77.0  3.4106  24.0  666.0
483   2.81838   0.0  18.10   0.0  0.532  5.762   40.3  4.0983  24.0  666.0
484   2.37857   0.0  18.10   0.0  0.583  5.871   41.9  3.7240  24.0  666.0
485   3.67367   0.0  18.10   0.0  0.583  6.312   51.9  3.9917  24.0  666.0
486   5.69175   0.0  18.10   0.0  0.583  6.114   79.8  3.5459  24.0  666.0
487   4.83567   0.0  18.10   0.0  0.583  5.905   53.2  3.1523  24.0  666.0
488   0.15086   0.0  27.74   0.0  0.609  5.454   92.7  1.8209   4.0  711.0
489   0.18337   0.0  27.74   0.0  0.609  5.414   98.3  1.7554   4.0  711.0
490   0.20746   0.0  27.74   0.0  0.609  5.093   98.0  1.8226   4.0  711.0
491   0.10574   0.0  27.74   0.0  0.609  5.983   98.8  1.8681   4.0  711.0
492   0.11132   0.0  27.74   0.0  0.609  5.983   83.5  2.1099   4.0  711.0
493   0.17331   0.0   9.69   0.0  0.585  5.707   54.0  2.3817   6.0  391.0
494   0.27957   0.0   9.69   0.0  0.585  5.926   42.6  2.3817   6.0  391.0
495   0.17899   0.0   9.69   0.0  0.585  5.670   28.8  2.7986   6.0  391.0
496   0.28960   0.0   9.69   0.0  0.585  5.390   72.9  2.7986   6.0  391.0
497   0.26838   0.0   9.69   0.0  0.585  5.794   70.6  2.8927   6.0  391.0
498   0.23912   0.0   9.69   0.0  0.585  6.019   65.3  2.4091   6.0  391.0
499   0.17783   0.0   9.69   0.0  0.585  5.569   73.5  2.3999   6.0  391.0
500   0.22438   0.0   9.69   0.0  0.585  6.027   79.7  2.4982   6.0  391.0
501   0.06263   0.0  11.93   0.0  0.573  6.593   69.1  2.4786   1.0  273.0
502   0.04527   0.0  11.93   0.0  0.573  6.120   76.7  2.2875   1.0  273.0
503   0.06076   0.0  11.93   0.0  0.573  6.976   91.0  2.1675   1.0  273.0
504   0.10959   0.0  11.93   0.0  0.573  6.794   89.3  2.3889   1.0  273.0
505   0.04741   0.0  11.93   0.0  0.573  6.030   80.8  2.5050   1.0  273.0

     PTRATIO       B  LSTAT
0       15.3  396.90   4.98
1       17.8  396.90   9.14
2       17.8  392.83   4.03
3       18.7  394.63   2.94
4       18.7  396.90   5.33
5       18.7  394.12   5.21
6       15.2  395.60  12.43
7       15.2  396.90  19.15
8       15.2  386.63  29.93
9       15.2  386.71  17.10
10      15.2  392.52  20.45
11      15.2  396.90  13.27
12      15.2  390.50  15.71
13      21.0  396.90   8.26
14      21.0  380.02  10.26
15      21.0  395.62   8.47
16      21.0  386.85   6.58
17      21.0  386.75  14.67
18      21.0  288.99  11.69
19      21.0  390.95  11.28
20      21.0  376.57  21.02
21      21.0  392.53  13.83
22      21.0  396.90  18.72
23      21.0  394.54  19.88
24      21.0  394.33  16.30
25      21.0  303.42  16.51
26      21.0  376.88  14.81
27      21.0  306.38  17.28
28      21.0  387.94  12.80
29      21.0  380.23  11.98
..       ...     ...    ...
476     20.2  396.21  18.68
477     20.2  349.48  24.91
478     20.2  379.70  18.03
479     20.2  383.32  13.11
480     20.2  396.90  10.74
481     20.2  393.07   7.74
482     20.2  395.28   7.01
483     20.2  392.92  10.42
484     20.2  370.73  13.34
485     20.2  388.62  10.58
486     20.2  392.68  14.98
487     20.2  388.22  11.45
488     20.1  395.09  18.06
489     20.1  344.05  23.97
490     20.1  318.43  29.68
491     20.1  390.11  18.07
492     20.1  396.90  13.35
493     19.2  396.90  12.01
494     19.2  396.90  13.59
495     19.2  393.29  17.60
496     19.2  396.90  21.14
497     19.2  396.90  14.10
498     19.2  396.90  12.92
499     19.2  395.77  15.10
500     19.2  396.90  14.33
501     21.0  391.99   9.67
502     21.0  396.90   9.08
503     21.0  396.90   5.64
504     21.0  393.45   6.48
505     21.0  396.90   7.88

[506 rows x 13 columns]>

In [15]:
y=pd.DataFrame(boston.target)
y.head()

      0
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [18]:
from sklearn.linear_model import LinearRegression
lm=LinearRegression()
lm.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [19]:
y_pred=lm.predict(X_test)
y_pred

array([[ 28.53469469],
       [ 36.6187006 ],
       [ 15.63751079],
       [ 25.5014496 ],
       [ 18.7096734 ],
       [ 23.16471591],
       [ 17.31011035],
       [ 14.07736367],
       [ 23.01064388],
       [ 20.54223482],
       [ 24.91632351],
       [ 18.41098052],
       [ -6.52079687],
       [ 21.83372604],
       [ 19.14903064],
       [ 26.0587322 ],
       [ 20.30232625],
       [  5.74943567],
       [ 40.33137811],
       [ 17.45791446],
       [ 27.47486665],
       [ 30.2170757 ],
       [ 10.80555625],
       [ 23.87721728],
       [ 17.99492211],
       [ 16.02608791],
       [ 23.268288  ],
       [ 14.36825207],
       [ 22.38116971],
       [ 19.3092068 ],
       [ 22.17284576],
       [ 25.05925441],
       [ 25.13780726],
       [ 18.46730198],
       [ 16.60405712],
       [ 17.46564046],
       [ 30.71367733],
       [ 20.05106788],
       [ 23.9897768 ],
       [ 24.94322408],
       [ 13.97945355],
       [ 31.64706967],
       [ 42.48057206],
       [ 17.70042814],
       [ 26.92507869],
       [ 17.15897719],
       [ 13.68918087],
       [ 26.14924245],
       [ 20.2782306 ],
       [ 29.99003492],
       [ 21.21260347],
       [ 34.03649185],
       [ 15.41837553],
       [ 25.95781061],
       [ 39.13897274],
       [ 22.96118424],
       [ 18.80310558],
       [ 33.07865362],
       [ 24.74384155],
       [ 12.83640958],
       [ 22.41963398],
       [ 30.64804979],
       [ 31.59567111],
       [ 16.34088197],
       [ 20.9504304 ],
       [ 16.70145875],
       [ 20.23215646],
       [ 26.1437865 ],
       [ 31.12160889],
       [ 11.89762768],
       [ 20.45432404],
       [ 27.48356359],
       [ 10.89034224],
       [ 16.77707214],
       [ 24.02593714],
       [  5.44691807],
       [ 21.35152331],
       [ 41.27267175],
       [ 18.13447647],
       [  9.8012101 ],
       [ 21.24024342],
       [ 13.02644969],
       [ 21.80198374],
       [  9.48201752],
       [ 22.99183857],
       [ 31.90465631],
       [ 18.95594718],
       [ 25.48515032],
       [ 29.49687019],
       [ 20.07282539],
       [ 25.5616062 ],
       [  5.59584382],
       [ 20.18410904],
       [ 15.08773299],
       [ 14.34562117],
       [ 20.85155407],
       [ 24.80149389],
       [ -0.19785401],
       [ 13.57649004],
       [ 15.64401679],
       [ 22.03765773],
       [ 24.70314482],
       [ 10.86409112],
       [ 19.60231067],
       [ 23.73429161],
       [ 12.08082177],
       [ 18.40997903],
       [ 25.4366158 ],
       [ 20.76506636],
       [ 24.68588237],
       [  7.4995836 ],
       [ 18.93015665],
       [ 21.70801764],
       [ 27.14350579],
       [ 31.93765208],
       [ 15.19483586],
       [ 34.01357428],
       [ 12.85763091],
       [ 21.06646184],
       [ 28.58470042],
       [ 15.77437534],
       [ 24.77512495],
       [  3.64655689],
       [ 23.91169589],
       [ 25.82292925],
       [ 23.03339677],
       [ 25.35158335],
       [ 33.05655447],
       [ 20.65930467],
       [ 38.18917361],
       [ 14.04714297],
       [ 25.26034469],
       [ 17.6138723 ],
       [ 20.60883766],
       [  9.8525544 ],
       [ 21.06756951],
       [ 22.20145587],
       [ 32.2920276 ],
       [ 31.57638342],
       [ 15.29265938],
       [ 16.7100235 ],
       [ 29.10550932],
       [ 25.17762329],
       [ 16.88159225],
       [  6.32621877],
       [ 26.70210263],
       [ 23.3525851 ],
       [ 17.24168182],
       [ 13.22815696],
       [ 39.49907507],
       [ 16.53528575],
       [ 18.14635902],
       [ 25.06620426],
       [ 23.70640231],
       [ 22.20167772],
       [ 21.22272327],
       [ 16.89825921],
       [ 23.15518273],
       [ 28.69699805],
       [  6.65526482],
       [ 23.98399958],
       [ 17.21004545],
       [ 21.0574427 ],
       [ 25.01734597],
       [ 27.65461859],
       [ 20.70205823],
       [ 40.38214871]])

In [20]:
y_test

        0
173  23.6
274  32.4
491  13.6
72   22.8
452  16.1
76   20.0
316  17.8
140  14.0
471  19.6
500  16.8
218  21.5
9    18.9
414   7.0
78   21.2
323  18.5
473  29.8
124  18.8
388  10.2
195  50.0
448  14.1
271  25.2
278  29.1
30   12.7
501  22.4
421  14.2
474  13.8
79   20.3
454  14.9
210  21.7
497  18.3
..    ...
57   31.6
194  29.1
24   15.6
17   17.5
298  22.5
66   19.4
211  19.3
404   8.5
94   20.6
154  17.0
441  17.1
23   14.5
225  50.0
433  14.3
447  12.6
5    28.7
116  21.2
45   19.3
16   23.1
468  19.1
360  25.0
3    33.4
405   5.0
185  29.6
60   18.7
110  21.7
321  23.1
265  22.8
29   21.0
262  48.8

[167 rows x 1 columns]

In [21]:
from sklearn.metrics import r2_score

In [22]:
r2_score(y_test,y_pred)

0.72615708365524867

In [23]:
ypred1=lm.predict([[0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98]])
ypred1

array([[ 29.99003492]])